/* TextResources - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */
package COM.stagecast.playwrite.internationalization;
import java.util.Hashtable;
import java.util.ListResourceBundle;

import COM.stagecast.playwrite.PlaywriteRoot;

public class TextResources extends ListResourceBundle
    implements ResourceIDs.AboutWindowIDs, ResourceIDs.CharacterVariableIDs,
	       ResourceIDs.CharacterWindowIDs, ResourceIDs.ColorIDs,
	       ResourceIDs.CommandIDs, ResourceIDs.ControlPanelIDs,
	       ResourceIDs.DialogIDs, ResourceIDs.DoorIDs,
	       ResourceIDs.DrawerIDs, ResourceIDs.DRTranslatorIDs,
	       ResourceIDs.ExamineWindowIDs, ResourceIDs.ExtensionIDs,
	       ResourceIDs.FileTransferIDs, ResourceIDs.FontIDs,
	       ResourceIDs.HelpWindowIDs, ResourceIDs.ImageIOIDs,
	       ResourceIDs.InstanceNameIDs, ResourceIDs.KeyIDs,
	       ResourceIDs.MenuIDs, ResourceIDs.NameGeneratorIDs,
	       ResourceIDs.OperationIDs, ResourceIDs.PicturePainterIDs,
	       ResourceIDs.RegistrationIDs, ResourceIDs.RootIDs,
	       ResourceIDs.RuleEditorIDs, ResourceIDs.RuleActionIDs,
	       ResourceIDs.RuleTestIDs, ResourceIDs.SimmerIDs,
	       ResourceIDs.SpecialCharIDs, ResourceIDs.SplashScreenIDs,
	       ResourceIDs.StageIDs, ResourceIDs.SummaryIDs,
	       ResourceIDs.SubroutineTypeIDs, ResourceIDs.TemplateIDs,
	       ResourceIDs.TextCharIDs, ResourceIDs.ToolIDs,
	       ResourceIDs.UnaryOpIDs, ResourceIDs.VariableIDs,
	       ResourceIDs.WorldVariableIDs, ResourceIDs.WorldIDs,
	       ResourceIDs.WorldViewIDs
{
    private static final String stagecastCopyright
	= "\u00a91998-2007 Stagecast Software, Inc. and its licensors. All rights reserved.";
    private static final String appleCopyright
	= "Portions \u00a91997 Apple Computer, Inc.";
    private static final String hurshCopyright
	= "Wav2Au software \u00a91997 Anthony Hursh";
    private static final String jpegCopyright
	= "JpegEncoder software \u00a91998 James R. Weeks and BioElectroMech";
    private static final String stagecastTrademark
	= "Stagecast, the Stagecast logo, Stagecast Creator, Stagecast Creator Pro, and Stagecast Player are trademarks of Stagecast Software, Inc.";
    private static final String whereToBuy
	= "To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder.";
    private static final Object[][] contents
	= { { "splash copyright notice",
	      "\u00a91998-2007 Stagecast Software, Inc. and its licensors. All rights reserved. Portions \u00a91997 Apple Computer, Inc." },
	    { "splash trademark notice",
	      "Stagecast, the Stagecast logo, Stagecast Creator, Stagecast Creator Pro, and Stagecast Player are trademarks of Stagecast Software, Inc." },
	    { "command c", "cancel" }, { "command copy", "copy" },
	    { "command cut", "cut" }, { "command d", "delete" },
	    { "command done", "done" }, { "command ds", "don't save" },
	    { "command g", "get" }, { "command import", "import" },
	    { "command n", "new" }, { "command no", "no" },
	    { "command ok", "ok" }, { "command p", "paste" },
	    { "command s", "save" }, { "command sa", "select all" },
	    { "command show appearance", "show an appearance" },
	    { "command sr", "show a rule" }, { "command u", "update" },
	    { "command y", "yes" }, { "command thumbnail", "thumbnail" },
	    { "command full size", "full size" },
	    { "command s2d", "save to disk" },
	    { "command s2i", "save to internet" },
	    { "command ap", "about {0}..." },
	    { "command api", "about plugins..." },
	    { "command aw", "about this sim..." },
	    { "command lc", "learn {0}..." },
	    { "command reset world", "reset" }, { "command nw", "new sim" },
	    { "command ow", "open sim..." }, { "command oaw", "open sim..." },
	    { "command osw", "open second sim..." },
	    { "command cw", "close sim" }, { "command s2s", "save remote" },
	    { "command sw", "save sim" }, { "command swa", "save sim as..." },
	    { "command swp", "publish..." }, { "command swpl", "local" },
	    { "command swpo", "other" }, { "command ss", "make report..." },
	    { "make snapshot", "make snapshot..." },
	    { "command pw", "disable changes..." },
	    { "command unprotect world", "enable changes..." },
	    { "command q", "quit" }, { "save as name generator", "{0} copy" },
	    { "splash lw", "Reading..." }, { "splash sw", "Writing..." },
	    { "startup progress bar", "Loading..." },
	    { "Font Family Courier", "courier" },
	    { "Font Family Helvetica", "helvetica" },
	    { "Font Family Times Roman", "times roman" },
	    { "Font Style Bold", "bold" },
	    { "Font Style Bold Italic", "bold italic" },
	    { "Font Style Italic", "italic" }, { "Font Style Plain", "plain" },
	    { "W iopd", "Pictures" }, { "W iobd", "Backgrounds" },
	    { "W iosd", "Sounds" }, { "W iowd", "Sims" },
	    { "W iousd", "Internet Sites" },
	    { "W wsr", "Save report for sim" },
	    { "menu mac accelerator key", "cmd+" },
	    { "menu win accelerator key", "ctrl+" },
	    { "splash cw", "create a sim" }, { "splash ow", "open a sim" },
	    { "splash ot", "learn {0}" }, { "splash q", "quit" },
	    { "splash b", "back" },
	    { "CP nc warn",
	      "Please click this tool on a stage, after board, or in the Characters drawer to create a new character type." },
	    { "CP ea warn",
	      "Please click this tool on a character to edit its picture." },
	    { "CP nr warn",
	      "Please click this tool on a character to give it a new rule." },
	    { "CP ct warn",
	      "Please click this tool on a copyable object to make a copy of it." },
	    { "CP ctp warn",
	      "Please click this in an empty space to place the copy." },
	    { "CP d warn",
	      "Please click this tool on a deletable object to remove it from the system." },
	    { "RE a", "actions" }, { "RE ai", "and if..." },
	    { "RE any", "any character" }, { "RE er", "edit" },
	    { "RE name", "name:" }, { "RE tr", "test" },
	    { "RE title", "Rule Maker" }, { "PE title", "Pretest Maker" },
	    { "RE dc warn",
	      "Please click this tool on a square in the 'before' picture to add the don't care attribute to it." },
	    { "RE mt warn",
	      "Please click this tool on a square in the 'before' picture to add a mouse test to the rule." },
	    { "RE e warn",
	      "Please click this tool on a square in the 'before' picture to compare it with the current stage." },
	    { "PE sv warn",
	      "Please click this tool on a character to see its variables." },
	    { "RE add", "add" }, { "RE create", "create" },
	    { "RE delete", "delete" }, { "RE from", "from" },
	    { "RE into", "into" }, { "RE move", "move" },
	    { "RE copy", "copy" }, { "RE on top", "on top" },
	    { "RE open url", "open url" }, { "RE put", "put" },
	    { "RE show", "show" }, { "RE split the stage", "split the stage" },
	    { "RE stages", "stages" }, { "RE subtract", "subtract" },
	    { "RE switch to stage", "switch to stage" },
	    { "RE through", "through" }, { "RE to", "to" },
	    { "RE transport", "transport" }, { "RE under", "under" },
	    { "RE underneath", "underneath" },
	    { "RE unsplit the stage", "unsplit the stage" },
	    { "RE any jar popup fmt", "any {0}" },
	    { "RE not Ruleaction class fmt",
	      "Extension class {0} does not inherit from {1}, so it could not be loaded." },
	    { "RE no method fmt",
	      "Extension class {0} does not declare a public static method called createForRuleEditor." },
	    { "RE bad method fmt",
	      "Extension class {0} declares createForRuleEditor but the signature is incorrect." },
	    { "mouse test xfmt", "<0> is clicked on <1>" },
	    { "key test fmt", "{0,choice,0#any|1#the {1}} key is pressed" },
	    { "RE ct warn",
	      "Character values may not be used unless the character is currently in the spotlight. Your rule test or action has been modified." },
	    { "drteleport action fmt", "Transport main character to <0>" },
	    { "copy action fmt", "copy <0> at <1>" },
	    { "create action fmt", "create <0> at <1>" },
	    { "delete action fmt", "delete <0>" },
	    { "move action fmt", "move <0> to <1>" },
	    { "open url action fmt", "open URL <0> in <1>" },
	    { "_self", "applet window" }, { "_parent", "parent frame" },
	    { "_top", "top frame" }, { "_blank", "new window" },
	    { "put action fmt", "<0> <!1> <2> <3>" },
	    { "put calc action fmt", "put <0> <1> <2> into <3>" },
	    { "put under action fmt", "put <0> under <1>" },
	    { "put on top action fmt", "put <0> on top" },
	    { "split stage action fmt",
	      "show {0,number,integer} {0,choice,1#stage|2#stages}" },
	    { "switch stage action fmt", "switch to stage <0>" },
	    { "teleport action 1 xfmt", "transport <0> through <1>" },
	    { "teleport action 2 xfmt", "transport <0> to <1>" },
	    { "stop action", "Stop" }, { "quit action", "Quit" },
	    { "operation summarizer format", "<0> {0} <1>" },
	    { "subtotal xfmt", "Subtotal {0}: <0>" },
	    { "total xfmt", "Calculation {0}: <0>" },
	    { "random xfmt", "Random number from <0> to <1>" }, { "+op", "+" },
	    { "-op", "-" }, { "*op", "*" }, { "/op", "\u00f7" },
	    { "==op", "is" }, { "!=op", "is not" }, { ">op", ">" },
	    { ">=op", ">=" }, { "<op", "<" }, { "<=op", "<=" },
	    { "Contains Op", "contains" },
	    { "does not Contain Op id", "does not contain" },
	    { "Contained By Op", "is contained in " },
	    { "Starts With Op", "starts with" },
	    { "Ends With Op", "ends with" }, { "Append Op", "append words" },
	    { "Remove Op", "remove last" }, { "Mod Op", "modulo" },
	    { "Power Op", "power" }, { "Remainder Op", "remainder" },
	    { "Round Op", "rounded to" }, { "Get Char # Op", "char #" },
	    { "Get Word # Op", "word #" }, { "Get Item # Op", "item #" },
	    { "Remove Char # Op", "remove char #" },
	    { "Remove Word # Op", "remove word #" },
	    { "Remove Item # Op", "remove item #" },
	    { "Append Char Op", "append chars" },
	    { "Append Item Op", "append items" },
	    { "Random Number Op", "random" },
	    { ResourceIDs.OperationIDs.SYS_CALC_ERROR_ID, "ERROR" },
	    { ResourceIDs.OperationIDs.SYS_CALC_TO_ID, "to" },
	    { ResourceIDs.UnaryOpIDs.SYS_UN_FUNC_XFMT_ID, "{1}(<0>)" },
	    { ResourceIDs.UnaryOpIDs.SYS_UN_PREFIX_XFMT_ID,
	      "{1}{0,choice,1#(2#}<0>{0,choice,1#)2#}" },
	    { ResourceIDs.UnaryOpIDs.SYS_UN_POSTFIX_XFMT_ID,
	      "{0,choice,1#(2#}<0>{0,choice,1#)2#}{1}" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_SIN_ID, "sin" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_COS_ID, "cos" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_TAN_ID, "tan" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_ASIN_ID, "asin" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_ACOS_ID, "acos" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_ATAN_ID, "atan" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_DEG_ID, "as radians" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_RAD_ID, "as degrees" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_SQRT_ID, "square root" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_NEG_ID, "negation" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_NUM_CHARS_ID, "# of chars" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_NUM_WORDS_ID, "# of words" },
	    { ResourceIDs.UnaryOpIDs.SYS_OP_NUM_ITEMS_ID, "# of items" },
	    { "return key id", "return" }, { "tab key id", "tab" },
	    { "backspace key id", "backspace" }, { "delete key id", "delete" },
	    { "escape key id", "escape" }, { "up-arrow key id", "up-arrow" },
	    { "down-arrow key id", "down-arrow" },
	    { "left-arrow key id", "left-arrow" },
	    { "right-arrow key id", "right-arrow" },
	    { "page-up key id", "page-up" },
	    { "page-down key id", "page-down" }, { "home key id", "home" },
	    { "end key id", "end" }, { "F1 key id", "F1" },
	    { "F2 key id", "F2" }, { "F3 key id", "F3" },
	    { "F4 key id", "F4" }, { "F5 key id", "F5" },
	    { "F6 key id", "F6" }, { "F7 key id", "F7" },
	    { "F8 key id", "F8" }, { "F9 key id", "F9" },
	    { "F10 key id", "F10" }, { "F11 key id", "F11" },
	    { "F12 key id", "F12" }, { "help key id", "help" },
	    { "enter key id", "enter" }, { "space key id", "space" },
	    { "shift key id", "shift-" }, { "control key id", "control-" },
	    { "command key id", "command-" }, { "meta key id", "meta-" },
	    { "option key id", "option-" }, { "alt key id", "alt-" },
	    { "key name format id", "{0}{1}" },
	    { "EW title", "Examine Square" }, { "EW stage", "stage has" },
	    { "EW rule", "rule wants" }, { "EW dc", "anything else" },
	    { "EW off",
	      "Wrapping is turned off, so this square is not on the stage." },
	    { "WW dm", "Drop a stage from the Stages Drawer here" },
	    { "WW Title", "new sim" },
	    { "WW Title Generator", "new sim {0, number, integer}" },
	    { "WW Timeout", "time out" },
	    { "WW world name fmt", "Stagecast: {0}" },
	    { "help window title bar", "Help" },
	    { "help window back button", "back" },
	    { "Picture Painter Title", "Picture Painter" },
	    { "Picture Painter new button", "new" },
	    { "Picture Painter get button", "get" },
	    { "Picture Painter Edit Menu", "edit" },
	    { "Picture Painter Fonts Menu", "font" },
	    { "Picture Painter Command Clear", "clear" },
	    { "Picture Painter Command Revert", "revert" },
	    { "Picture Painter Command Undo", "undo" },
	    { "Picture Painter Alert 1",
	      "Pictures may not be blank. Please fill in blank pictures or delete them before closing the Picture Painter." },
	    { "Picture Painter Alert 2",
	      "You have changed the shape of this picture. Rules that use it must be updated. This may take a while." },
	    { "Picture Painter Alert 3",
	      "This picture is too large, so it has been trimmed to fit." },
	    { "Picture Painter Alert 4",
	      "Sorry, two pictures may not have the same name." },
	    { "Picture Painter Alert 5",
	      "Due to differences in square size, this new picture is too large, so it has been trimmed to fit." },
	    { "Picture Painter Alert 6",
	      "Sorry, the Picture Painter cannot edit this character's pictures because some of the pictures are too large." },
	    { "Picture Painter Alert 7",
	      "Sorry, the anchor square must not be empty. Please choose a nonempty square." },
	    { "PP update", "Updating Rules" },
	    { "Picture Painter Command Flip Horizontal", "flip horizontal" },
	    { "Picture Painter Command Flip Vertical", "flip vertical" },
	    { "Picture Painter Command Rotate", "rotate" },
	    { "Picture Painter Command Stretch", "stretch" },
	    { "Picture Painter Command Left Justify", "left" },
	    { "Picture Painter Command Center Justify", "center" },
	    { "Picture Painter Command Right Justify", "right" },
	    { "drawer ct", "Characters" }, { "drawer spt", "Special" },
	    { "drawer stt", "Stages" }, { "drawer sot", "Sounds" },
	    { "drawer jt", "Jars" }, { "drawer gt", "Global" },
	    { "drawer gsl", "get" }, { "sound new", "new" },
	    { "sound import dialog title", "Import Sound" },
	    { "sound import all dialog title", "Import All Sounds" },
	    { "sound repl", "replace" }, { "drawer new stage button", "new" },
	    { "drawer new jar button", "new" }, { "NamVarID", "name" },
	    { "AppVarID", "appearance" }, { "SndVarID", "sound" },
	    { "HvarID", "horizontal" }, { "VvarID", "vertical" },
	    { "StgVarID", "stage" }, { "ROAppVarID", "rollover" },
	    { "ROEnVarID", "rollover enabled" },
	    { "RODiVarID", "rollover disabled" },
	    { "type of character", "type of character" },
	    { "WNamVarID", "sim name" }, { "WFMVarID", "follow me" },
	    { "WCVarID", "window color" }, { "WFRVarID", "frame rate" },
	    { "WSVarID", "speed" }, { "WHSVarID", "history size" },
	    { "WSimVarID", "maximum input delay" },
	    { "WEnvVarID", "environment" }, { "WEnvFmtID", "{0},{1},{2}" },
	    { "WAppParamID", "applet parameter" },
	    { "GetBackgID", "get background" },
	    { "GetAllBgsID", "get all backgrounds" },
	    { "NewVarNamID", "variable {0}" },
	    { "VarWinTitleID", "{0} : Variables" }, { "NoValue ID", "?" },
	    { "WPSTVarID", "playing sounds" },
	    { "WPSFVarID", "not playing sounds" },
	    { "WSATVarID", "moving one at a time" },
	    { "WSAFVarID", "moving at the same time" },
	    { "WXASTVarID", "running all stages" },
	    { "WXASFVarID", "running only visible stages" },
	    { "WSGTVarID", "showing grid" }, { "WSGFVarID", "hiding grid" },
	    { "WLockedVarID", "locked" }, { "WUnockedVarID", "unlocked" },
	    { "WCenterFollowMeTVarID", "center follow me" },
	    { "WCenterFollowMeFVarID", "don't center follow me" },
	    { "stage name gererator", "stage {0, number, integer}" },
	    { "SBGVarID", "background" },
	    { "BGAlignVarID", "background position" },
	    { "BGColorVarID", "background color" },
	    { "STG ABC ID", "centered" }, { "STG ABT ID", "tiled" },
	    { "STG ABS ID", "scaled to fit" },
	    { "SWLRTVarID", "wrapping left-right" },
	    { "SWLRFVarID", "not wrapping left-right" },
	    { "SWUDTVarID", "wrapping up-down" },
	    { "SWUDFVarID", "not wrapping up-down" },
	    { "SWVarID", "stage width" }, { "SHVarID", "stage height" },
	    { "SSqSzVarID", "square size" },
	    { "text character name id", "text" }, { "TXTtxtID", "text" },
	    { "TXTfontID", "text font" }, { "TXTsizeID", "text size" },
	    { "TXTstyleID", "style" }, { "TXTalignmentID", "alignment" },
	    { "TXTalignleftID", "left" }, { "TXTalignrightID", "right" },
	    { "TXTaligncenterID", "center" },
	    { "TXT offset X ID", "offset X" },
	    { "TXT offset Y ID", "offset Y" }, { "TXTcolorID", "text color" },
	    { "TXTbgcolorID", "background color" }, { "TXTwidthID", "width" },
	    { "TXTheightID", "height" }, { "TXTroTID", "can be changed" },
	    { "TXTroFID", "can't be changed" },
	    { "TXT border true ID", "show border" },
	    { "TXT border false ID", "hide border" },
	    { "TXT shrink_to_fit true ID", "auto-size text" },
	    { "TXT shrink_to_fit false ID", "don't auto-size text" },
	    { "TXT was_changed true ID", "text has changed" },
	    { "TXT was_changed false ID", "text has not changed" },
	    { "TXT default text", "abc" },
	    { "type da", "do all and continue" }, { "type df", "do first" },
	    { "type dit", "do in turn" }, { "type dr", "do random" },
	    { "Generator an", "picture {0, number, integer}" },
	    { "Generator cin", "copy of {0}" },
	    { "Generator cin2", "copy {1, number, integer} of {0}" },
	    { "Generator nin", "{0} {1, number, integer}" },
	    { "Generator cpn", "character {0, number, integer}" },
	    { "Generator scpn", "special character {0, number, integer}" },
	    { "Generator cin3", "{0}-{1, number}" },
	    { "cwNSN", "untitled {0,number,integer}" },
	    { "character window new rule", "untitled rule" },
	    { "character window type a comment", "type a comment here" },
	    { "cwCWarn",
	      "Please click this tool on a rule or rule box to add a comment." },
	    { "cwPWarn",
	      "Please click this tool on a rule box to add a pretest." },
	    { "cwDWarn",
	      "Please click this tool on a rule or rule box to disable it." },
	    { "cwBpWarn",
	      "Please click this tool on a rule or rule box to set or clear a breakpoint." },
	    { "door default appearance", "door" },
	    { "door end appearance", "door end" }, { "door name", "door" },
	    { "door end name", "end of {0}" },
	    { "Generator jar Name", "Jar {0, number, integer}" },
	    { "Generator sn", "sound" }, { "variable", "variable" },
	    { "NewColorID", "new color" }, { "ThisColorID", "this color" },
	    { "TransparentCID", "transparent" },
	    { "Def CID", "default color" }, { "BlackID", "black" },
	    { "WhiteID", "white" }, { "darkGray CID", "dark gray" },
	    { "gray CID", "gray" }, { "lt Gray CID", "light gray" },
	    { "mgnta CID", "magenta" }, { "blu CID", "blue" },
	    { "CY CID", "cyan" }, { "GRN CID", "green" },
	    { "Yelo CID", "yellow" }, { "Orng CID", "orange" },
	    { "Red CID", "red" }, { "Pnk CID", "pink" },
	    { "Purp CID", "purple" }, { "INST noso ID", "no sound" },
	    { "INST nobg ID", "no background" },
	    { "REFOBJ app ID", "appearance" },
	    { "REFOBJ pro ID", "type of character" },
	    { "REFOBJ jar ID", "jar" }, { "REFOBJ sou ID", "sound" },
	    { "REFOBJ stg ID", "stage" }, { "REFOBJ var ID", "variable" },
	    { "gray splat", "gray splat" },
	    { "current board", "current board" },
	    { "dialog banr",
	      "Appearance {0} was malformed and has been deleted." },
	    { "dialog baar",
	      "Appearance {0} was malformed and has been deleted along with {1,number,integer} rules that refer to it:" },
	    { "dialog barr", "{0,number,integer}) {1} in {2}.\n" },
	    { "dialog ba",
	      "The sim you just opened contains one or more malformed appearances. The following rules that referred to them have been deleted in order to repair the sim: " },
	    { "dialog bad cv",
	      "This sim contained {0} case{0,choice,0#s|1#|2#s} in which a rule test or action with the ''follow me'' variable illegally used a character value.  These characters have been removed from the rules. You may need to edit the rules to get the sim to operate correctly." },
	    { "dialog bif",
	      "Sorry, the image file you chose is not readable. It must be in GIF or JPEG format. Animated GIFs are not supported." },
	    { "dialog bsf",
	      "Sorry, the sound file you chose is not in a format that we understand." },
	    { "dialog burl", "Sorry, the URL provided is not legal: " },
	    { "dialog badW",
	      "Sorry, this sim contains serious errors and cannot be repaired." },
	    { "dialog badCW",
	      "Sorry, this Cocoa sim contains serious errors and cannot be repaired." },
	    { "dialog ccgc",
	      "Sorry, you may not modify characters on the left side of a rule." },
	    { "dialog cc", "Sorry, couldn't connect to URL: " },
	    { "dialog cff", "Sorry, couldn''t find the file: {0}" },
	    { "dialog cft",
	      "Sorry, the tutorial files can't be found.  To learn Creator over the web, go to http://www.stagecast.com/tutorial/" },
	    { "dialog cof", "Sorry, couldn't open the file: " },
	    { "dialog coo",
	      "Sorry, you can not publish over the original sim.  Please choose a different file name or save to another folder." },
	    { "dialog cstr",
	      "Sorry, the file you have chosen is locked or on a read-only volume such as a write-protected server folder or CD-ROM. Please try again." },
	    { "dialog cil",
	      "Sorry, this character is protected. Please select it and choose the Unprotect command in the menu if you wish to open it." },
	    { "dialog caw", "Please choose a sim to open" },
	    { "dialog cap", "Please choose a picture" },
	    { "dialog choose all pictures",
	      "Please choose an image file (import all)" },
	    { "dialog cab", "Please choose a background" },
	    { "dialog cabf", "Please choose a background (import all)" },
	    { "dialog cct", "Color Chooser" },
	    { "dialog cd1t",
	      "Your display is set to 16 Color. Please change your display settings to High Color (16-bit) or 24-bit True Color and try again. If you continue, {0} may not operate correctly. " },
	    { "dialog cd1b", "quit" },
	    { "dialog cd2t",
	      "Your display is set to {1, choice, 8#16 or 256 Color|32#True Color (32-bit)}. To display colors in {0} correctly, please change your display settings to {2, choice, 0#High Color (16-bit) or 24-bit True Color |1#True Color (24-bit or 32-bit)|2#High Color (16-bit) or True Color (24-bit or 32-bit)} before using {0}." },
	    { "dialog cd2b1", "continue" }, { "dialog cd2b2", "quit" },
	    { "dialog cd3t",
	      "Your display is set to High Color (16 bit). Testing has shown that this version of Java causes some machines to freeze unexpectedly. We strongly recommend you change your display settings to True Color (24-bit or 32-bit) before using {0}." },
	    { "dialog cd3b1", "continue" }, { "dialog cd3b2", "quit" },
	    { "dialog cwe",
	      "Welcome to the {0} of {1}. This {0} will expire on {2}. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog cew", "This {0} of {1} will expire on {2}." },
	    { "dialog cto",
	      "This {0} of {1} has timed out. Please check our Web site at www.stagecast.com for information on updates. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog dce",
	      "A copy of {0} ''{1}'' already exists.  It is named ''{4}'' and cannot be replaced. You must delete ''{4}'' in sim ''{2}'' before dragging in ''{1}''.  Or, to make a new {0}, first use the copy tool to make a copy of ''{1}'' in sim ''{3}'' and then drag the new copy into ''{2}''." },
	    { "dialog ebc",
	      "Please click on the edit button before changing this variable." },
	    { "dialog ebg",
	      "Please click on the edit button before generalizing this character." },
	    { "dialog ebo",
	      "Please click on the edit button before opening this character." },
	    { "dialog eval limit prototype",
	      "Sorry, this is the {0}. You may not create more than {1, number, integer} types of characters in it. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog eval limit rule",
	      "Sorry, this is the {0}. You may not create more than {1, number, integer} rules in it. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog eval limit stage",
	      "Sorry, this is the {0}. You may not create more than {1, number, integer} stages in it. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog eval cant save",
	      "Sorry, this is the {0}. You are not allowed to save in it. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog fatal title", "Fatal Error" },
	    { "dialog fatal 1 text",
	      "Sorry, an unexpected error has occurred. This application will now quit. You may try to save your sim. However, it may not be usable, so please save it with a different name." },
	    { "dialog fatal 1 text mac",
	      "Sorry, an unexpected error has occurred. There may not be enough memory to run this application. This application will now quit. You may try to save your sim. However, it may not be usable, so please save it with a different name." },
	    { "dialog fatal 1 button 1", "save and quit" },
	    { "dialog fatal 1 button 2", "quit" },
	    { "dialog fatal 2 text",
	      "Sorry, an unexpected error has occurred. This application will now quit." },
	    { "dialog fatal 2 text mac",
	      "Sorry, an unexpected error has occurred. There may not be enough memory to run this application. This application will now quit." },
	    { "dialog fatal 2 button", "quit" },
	    { "dialog fatal 3 text",
	      "Sorry, an unexpected error has occurred. Please reload the applet by clicking the Refresh button in your browser." },
	    { "dialog fatal 3 button", "ok" },
	    { "dialog fatal 4 text",
	      "Sorry, an unexpected error has occurred. There may not be enough memory to run this application." },
	    { "dialog fatal 4 button", "quit" },
	    { "dialog ioe",
	      "Sorry, an I/O error occurred while reading this sim." },
	    { "dialog iil",
	      "Sorry, this item is protected. Please select it and choose the Unprotect command in the menu if you wish to open it." },
	    { "dialog ls",
	      "The file you have selected is very large, importing it may take a long time and systems with limited memory may crash.  Do you want to go ahead and import this file?" },
	    { "dialog mlm",
	      "You are about to run out of memory. Please close all windows and save your work. Then quit and restart." },
	    { "dialog mlmp",
	      "Stagecast Player is running out of memory. You may need to quit other applications or increase virtual memory to run large sims." },
	    { "dialog max windows",
	      "More than {0} windows are open. Please close an existing window before opening a new one." },
	    { "dialog no character window in player",
	      "Sorry, double-clicking doesn't do anything in Stagecast Player. If you want to see a character's rules, you need to use Stagecast Creator." },
	    { "dialog no image access",
	      "Sorry, essential image files were not found. There is a problem with the installation of your Stagecast software or with your system's software package management. Please see www.stagecast.com/webhelp for more information." },
	    { "dialog nmk",
	      "Sorry, you can't use modifier keys when editing text." },
	    { "dialog nwc",
	      "A working copy of this sim could not be created. Please use 'Save As' to save this sim with a different name. Do not use 'Save'." },
	    { "dialog no world window active",
	      "Please click in a window before using this command." },
	    { "dialog na",
	      "Sorry, Java security does not allow access to file: " },
	    { "dialog niw",
	      "This character has not been copied into this sim yet. Please open the sim that contains it and copy it into this sim." },
	    { "dialog ns", "Sorry, this object cannot be selected." },
	    { "dialog num?", "Sorry, numbers can't be formatted this way." },
	    { "dialog ocw", "Opening Character Window" },
	    { "dialog pi", "Sorry, that was not the correct password." },
	    { "dialog pak", "Please press a key to use." },
	    { "dialog pak any", "any key" },
	    { "dialog pos",
	      "Please put this character on a stage before changing its stage variable." },
	    { "dialog rdp",
	      "Are you sure you want to delete this type of character? All of its copies will be deleted too. This cannot be undone." },
	    { "dialog rds",
	      "Are you sure you want to delete this stage? All of the characters on it will be deleted too. This cannot be undone." },
	    { "dialog rpl",
	      "The sim you saved will not run for another user unless the following plugin(s) are present on that machine: \n" },
	    { "dialog rdc",
	      "One or more characters have been deleted due to the change in stage size. You can undo this by playing backwards one step." },
	    { "dialog rhna",
	      "This rule has no actions. Are you done with it?" },
	    { "dialog ril",
	      "Sorry, this rule is protected. Please select it and choose the Unprotect command in the menu if you wish to open it." },
	    { "dialog part of spotlight not on stage",
	      "Sorry, this square is off the stage. Nothing can be dropped on it." },
	    { "dialog rrt",
	      "{0,number,integer} {0,choice,1#rule refers|2#rules refer} to this {1}. Please remove {0,choice,1#that reference|2#those references} and then try deleting again." },
	    { "dialog appearance ref variable",
	      "{0,number,integer} {0,choice,1#picture displays|pictures display} this variable. Please remove {0,choice,1#that reference|2#those references} and then try deleting again." },
	    { "dialog sbh",
	      "Please save your changes before putting the sim on the Web." },
	    { "dialog slw",
	      "Save the Web page on a local disk or on the Internet?" },
	    { "dialog sc", "Save changes to this sim before closing?" },
	    { "dialog scon",
	      "This file is a Creator 1.0 world.  It may take some time to save it as a sim.  Please be patient." },
	    { "dialog sf",
	      "Sorry, an error occurred while attempting to save this sim." },
	    { "dialog choose image size", "Please choose the image size." },
	    { "dialog attempt to make snapshot has failed",
	      "Sorry, an error occurred while attempting to make a snapshot." },
	    { "dialog ss", "Please select something to delete." },
	    { "dialog sne",
	      "Sorry, this serial number has expired. The program will revert to a free trial version." },
	    { "dialog sp",
	      "If you wish to protect this with a password, please type it below." },
	    { "dialog set password confirm",
	      "Please type the password again to confirm it." },
	    { "dialog gp", "Please type the password below." },
	    { "dialog snor",
	      "Would you like to create a new sound or replace the selected sound?" },
	    { "cwNoShoVars",
	      "Sorry, this Character Window isn't tall enough to show variables. Please make it taller and try again." },
	    { "dialog stage max width",
	      "Sorry, a stage cannot be wider than {0, number, integer} squares." },
	    { "dialog stage min width",
	      "A Stage must be at least {0, number, integer} squares wide." },
	    { "dialog stage max height",
	      "Sorry, a stage cannot be higher than {0, number, integer} squares." },
	    { "dialog stage min height",
	      "A Stage must be at least {0, number, integer} squares high." },
	    { "dialog stage max sqare sz",
	      "The largest square size is {0, number, integer}." },
	    { "dialog stage min sqare sz",
	      "The smallest square size is {0, number, integer}." },
	    { "dialog se",
	      "Sorry, an error occurred while trying to write the summary to disk." },
	    { "dialog tbdw",
	      "The test button works only for characters on a stage." },
	    { "dialog to",
	      "Sorry, this free test version has timed out. Please check our Web site at www.stagecast.com for information on updates. To purchase a fully enabled copy of this program, see the 'WhereToBuy' text file in the Stagecast folder." },
	    { "dialog us",
	      "Please use shift-select only on items in the same stage or drawer." },
	    { "dialog us-mac",
	      "Please use shift-select only on items in the same stage or drawer. Be sure the 'caps lock' key is not down when using the mouse." },
	    { "dialog ue",
	      "Sorry, an error occurred while attempting to read this sim." },
	    { "dialog uf", "Sorry, this sim is not in a known format." },
	    { "dialog ve",
	      "Sorry, this sim was created by a newer version of this product. Please run that version in order to read it." },
	    { "dialog wil",
	      "Sorry, this sim is protected. Please save it under a different name." },
	    { "dialog !cco",
	      "Sorry, this sim is not in Cocoa's Save For Internet format. Please open it in Cocoa and choose 'Save For Internet' to make a .cco file." },
	    { "dialog dltNP",
	      "Sorry, items cannot be deleted while using breakpoints." },
	    { "dialog cpyNP",
	      "Sorry, items cannot be copied while using breakpoints." },
	    { "dialog toolNP",
	      "Sorry, this tool cannot be used while using breakpoints." },
	    { "dialog noDragNP",
	      "Sorry, items cannot be dragged while using breakpoints." },
	    { "dialog bad world with name",
	      "The sim named ''{0}'' has been repaired. To avoid further problems, please save it immediately with a different name, and use the new copy.\n" },
	    { "dialog bad world",
	      "The sim you just read in has been repaired. To avoid further problems, please save it immediately with a different name, and use the new copy.\n" },
	    { "dialog sver temp",
	      "Sorry, couldn''t get the template file {0}." },
	    { "dialog sver html",
	      "Sorry, couldn''t write the required HTML file: {0}." },
	    { "dialog sver plug",
	      "Sorry, couldn''t write the required plugins: {0}." },
	    { "dialog sver wrld", "Sorry, couldn''t write the sim: {0}." },
	    { "dialog sver appl",
	      "Sorry, couldn''t write the applet file: {0}." },
	    { "dialog ver del sub",
	      "You cannot undo this action.  Do you wish to delete this subroutine and all its rules?" },
	    { "dialog web conn",
	      "Please make sure you have a live Internet connection." },
	    { "drRMWT", "Translation Report" },
	    { "drRM0",
	      "Sorry, your Cocoa sim could not be fully translated. To save this text, cut and paste it into another application.\n" },
	    { "drRM2", "{0} was malformed and was deleted.\n" },
	    { "drRM1",
	      "{0,number,integer} rules that referred to {1} were deleted:\n" },
	    { "drRM10", "{0} in {1} was deleted.\n" }, { "drRM3", "Sound" },
	    { "drRM4", "Rule" }, { "drRM5", "Type" },
	    { "drRM6",
	      "Sorry, there were problems translating this Cocoa sim. It may not work properly." },
	    { "drRM7", "{0} ''{1}''" },
	    { "drRM8",
	      "Translation Report for Cocoa Sim ''{0}''\n Produced by {1} {2} build {3}\n at {4,time, short} on {4,date,full}\n" },
	    { "drRM9",
	      "Due to an error in the Cocoa file, the avatar character was not created. To set the avatar, open the sidelines, open the 'global' drawer, and drop the avatar character in the 'follow me' variable." },
	    { "drRM12",
	      "Due to an error in the Cocoa file, the avatar could not be set. To set the avatar, open the sidelines, open the 'global' drawer, and drop the avatar character in the 'follow me' variable." },
	    { "copy of ", "copy of " }, { "W ex", ".sim" },
	    { "TT close world", "close this sim" },
	    { "TT done", "close and save changes" },
	    { "TT cancel", "close and throw away changes" },
	    { "reg ti", "Register" },
	    { "reg ms",
	      "Thank you for purchasing a Stagecast product. Please enter your name and the serial number (found on the CD-ROM sleeve) that came with your purchase:" },
	    { "reg nl", " Name: " }, { "reg sl", " Serial number: " },
	    { "regb re", "register" }, { "regb can", "cancel" },
	    { "regb ok", "ok" },
	    { "reg fa",
	      "Sorry, that is not a valid registration number. This program will not run without a proper serial number." },
	    { "SUM pc",
	      "{0,number,integer} character type{1,choice,0#s|1#|2#s}" },
	    { "SUM pl",
	      "; {0,number,integer} more can be created in this trial version" },
	    { "SUM rc", "{0,number,integer} rule{1,choice,0#s|1#|2#s}" },
	    { "SUM rl",
	      "; {0,number,integer} more can be created in this trial version" },
	    { "SUM sc", "{0,number,integer} stage{1,choice,0#s|1#|2#s}" },
	    { "SUM sl",
	      "; {0,number,integer} more can be created in this trial version" },
	    { "SUM cs", "Characters" },
	    { "SUM ure", "Unknown rule extension" },
	    { "SUM aa", "any appearance" }, { "SUM andif", "and if" },
	    { "SUM do", "do" }, { "SUM testerr", " ** error in rule test **" },
	    { "SUM acterr", " ** error in action **" },
	    { "SUM suberr", " ** error in subroutine **" },
	    { "SUM apperr", " ** error in appearances **" },
	    { "SUM ah", "{0} appearances" },
	    { "SUM varerr", " ** error in variable **" },
	    { "SUM vh", "{0} variables" }, { "SUM ss", "Stages" },
	    { "SUM stgerr", " ** error in stages **" }, { "SUM js", "Jars" },
	    { "SUM gs", "Global" }, { "SUM gvar", "Global" },
	    { "SUM gc a", "any character" },
	    { "SUM gc j", "any character in jar {0}" },
	    { "SUM mct", "the mouse is clicked" }, { "SUM mva", "my {0}" },
	    { "SUM twv", "this sim''s {0}" }, { "SUM pva", "''s {0}" },
	    { "SUM wcb", "Created in: " }, { "SUM wsb", "Last saved in: " },
	    { "SUM null", "?" }, { "FTP dt", "Publish to {0}" },
	    { "FTP duh", "Internet" }, { "FTP hf", "Host:" },
	    { "FTP uf", "User:" }, { "FTP udf", "Directory:" },
	    { "FTP pf", "Password:" }, { "FTP pt", "Sending {0}" },
	    { "FTP ute",
	      "Sorry, unable to get the most recent HTML template file from {0}." },
	    { "FTP utb", "Use local copy" },
	    { "FTP tm",
	      "Sorry, the template file for the selected site ({0}) cannot be found." },
	    { "FTP hm", " For additional assistance, please check at {0}" },
	    { "EXT mea",
	      "Sorry, the sim refers to an extension. Sims with extensions cannot be run over the Internet." },
	    { "EXT me",
	      "Sorry, the following extension was referenced but failed to load: {0}." },
	    { "EXT meu",
	      "Sorry, the following extension was referenced but failed to load: {0}. Please check at {1} for more information." },
	    { "EXT pv", "{0} version {1, number, integer}" },
	    { "EXT pnf", "No plug-ins were found." },
	    { "root vn", "Version {0}" }, { "root rn", "Release {0}" },
	    { "root bn", "Build {0}" }, { "root cpn", "Creator" },
	    { "root ppn", "Player" }, { "root sapn", "Creator Pro" },
	    { "root sspn", "InstantSim Server" },
	    { "root pts", "standard version" },
	    { "root ptd", "evaluation version" },
	    { "root ptp", "pre-release version" },
	    { "about wint", "About {0}" }, { "about pt", "About Plugins" },
	    { "about atem", "Your Name" }, { "about a", "by" },
	    { "about c", "Comment" }, { "about cred", "Created with {0}" },
	    { "about ctem", "" },
	    { "at_std",
	      "<APPLET\n    code=\"StagecastApplet.class\"\n    archive=\"StagecastApplet.jar{1}\"\n    {4}\n    width={2, number, ####0} height={3, number, ####0}>\n        <param name=\"ApplicationClass\" value=\"com.stagecast.creator.PlayerApplet\">\n        <param name=\"VersionNeeded\" value=\"{5}\">\n        <param name=\"AutoInstall\" value=\"{6}\">\n        <param name=\"InstallerURL\" value=\"http://www.stagecast.com/installplayer/\">\n        <param name=\"World\" value=\"{0}\">\n        {8}\n</APPLET>\n" },
	    { "about b",
	      "{0} was invented by Allen Cypher and David Canfield Smith.\n\n" },
	    { "about bc",
	      "President of Stagecast Software, Inc.\n\tLarry Tesler\n\nPrincipal Designers and Implementers, in alphabetical order\n\tNikolaus Heger\n\tFidelia Kuang\n\tRoss Nelson\n\tScott Posey\n\nTutorial\n\tJeffrey Tribble\n\nStagecast staff\n\tNathan Anderson, Ora Chaiken, Ray Davis, Diane Griffith, Donna Hendrickson, Susan Lee-Merrow, Debbie Miller, Constance Nguyen, Vicki Parish, Mike Pearce, Mary Reagan, Sharon Vazquez\n\nAnd a special thanks to all of our beta testers!\n\nStagecast, the Stagecast logo, Stagecast Creator, Stagecast Creator Pro, and Stagecast Player are trademarks of Stagecast Software, Inc.\n\n\u00a91998-2007 Stagecast Software, Inc. and its licensors. All rights reserved.\nPortions \u00a91997 Apple Computer, Inc.\nWav2Au software \u00a91997 Anthony Hursh\nJpegEncoder software \u00a91998 James R. Weeks and BioElectroMech\n" },
	    { "slmfid1", "{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t" },
	    { "slmfid2", "{0}\t{1}\t{2}\t{3}\t{4}\t{5}" },
	    { "slmevt", "{0}\t{1}\t{2}\t{3}\t{4}\t{5}" } };
    
    static {
	if (PlaywriteRoot.isCustomerBuild() == false) {
	    boolean throwException = false;
	    Hashtable ourResourcesTable = new Hashtable(contents.length);
	    for (int i = 0; i < contents.length; i++) {
		if (ourResourcesTable.contains(contents[i][0]) == true) {
		    String message
			= ("Duplicate resource found in " + TextResources.class
			   + ": " + contents[i][0]);
		    System.err.println(message);
		    throwException = true;
		}
		ourResourcesTable.put(contents[i][0], contents[i][0]);
	    }
	    if (throwException == true)
		throw new RuntimeException
			  ("Invalid resources found in " + TextResources.class
			   + ". See System.err output for details.");
	}
    }
    
    public Object[][] getContents() {
	return contents;
    }
}
